### ISSUE TITLE
No `electron.asar` in Chat.app version 20.1.71

### ISSUE THREAD

**Issue by wjhrdy** [paveyry/better-hangoutschat#10]
Just updated and the resources folder doesn't seem to have an `electron.asar` file.

**Comment by GeffenMetzger** [comment]
Same issue here, no electron.asar file. Forgot how blinding the default chat client is.

**Comment by paveyry** [comment]
I'm looking into it but for some reason the latest version I can get is still 19.*

**Comment by tvories** [comment]
@paveyry https://dl.google.com/chat/20.1.71/InstallHangoutsChat.dmg is the direct link to the Mac version.

**Comment by paveyry** [comment]
Thanks. I've looked into the new code organisation and tried to add the custom code but so far I'm having no luck. I wonder if they did this on purpose to avoid plugins. 
If anybody finds how/where I can inject the code, I'm open to suggestions.

**Comment by paveyry** [comment]
In the meantime, it seems version 19.9.101 is still working perfectly fine so you can probably download it and use it until we find a solution. https://dl.google.com/chat/19.9.101/InstallHangoutsChat.dmg

**Comment by paveyry** [comment]
Also, the tampermonkey/greasemonkey scripts still work perfectly fine. If you want it in a standalone process/window without the Chrome GUI, you can run `google-chrome --app=https://chat.google.com` on GNU/Linux or `open -a "Google Chrome" --args --app=https://chat.google.com` on macOS

**Comment by paveyry** [comment]
With the help of @elanini who found a way to inject the code via the app/main.js file, I've pushed a new commit and published a new release. The file to change is now `Chat.app/Contents/Resources/app/main.js` instead of `electron.asar` but everything else is identical and working perfectly. 
You can also simply clone the repository and run `make install` on Mac, as detailed in `README.md`
