### ISSUE TITLE
Main.js replacement causes constant update request

### ISSUE THREAD

**Issue by iFixRobots** [paveyry/better-hangoutschat#11]
As the title mentions, after the previous found fix for the electron issue, the app is constantly request upgrades every x amount of time once you replace the main.js. 

Looks like something in the old main.js is not matching up to the new one.

**Comment by paveyry** [comment]
It seems Google is rolling updates here in Europe later, that's why I haven't hit it yet and why it took me a while to discover about the `electron.asar` disappearance. I just pushed a new tag, the CI should deploy a new patched version (tag v4.0.2) with the latest `main.js`. 

Alternatively you can clone the repository and follow the instructions in section `Building Electron Client patch from source` from the README. This will patch from your local version and should work fine. Let me know if the issue stays despite this.

**Comment by paveyry** [comment]
For more clarity, releases' name will now include the GHC build version.
