### ISSUE TITLE
gmonkey script

### ISSUE THREAD

**Issue by harriee26** [paveyry/better-hangoutschat#19]
This has been a wonderful patch and been using for so long but since start of April https://chat.google.com is being redirected to https://mail.google.com/chat/u/0/#chat/welcome. Since then gmonkeyscript doesn't work any more. Can you please check and fix? Thanks in advance.

**Comment by paveyry** [comment]
Yes, I am aware of this issue and I am working on it. I still don't have the update on my account, as it seems that Google does not roll the update to everybody at the same time, but I finally found a way to access it anyway a few days ago, so I should be able to fix it fairly soon.

**Comment by paveyry** [comment]
Release v6.0.1 should fix this.
It is now updated for the latest GHC update. However, the firefox extension has not been updated yet, for now it is only the gmonkeyscript. Also, the one-click copy button for thread links is gone, due to google moving the content of the chat within an iframe from a different domain, which prevents access to the clipboard due to content policy.
https://github.com/paveyry/better-hangoutschat/releases/tag/v6.0.1

**Comment by paveyry** [comment]
Actually the browser extension is now working fine with release v6.0.2
https://github.com/paveyry/better-hangoutschat/releases/tag/v6.0.2
